/**
 * Builds TypeScript plugins into AMD modules for WebGME.
 */
import { readFileSync } from 'fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import commonjs from '@rollup/plugin-commonjs';
import json from '@rollup/plugin-json';
import resolve from '@rollup/plugin-node-resolve';
import typescript from '@rollup/plugin-typescript';
import copy from 'rollup-plugin-copy';

const webgmeSetup = JSON.parse(readFileSync('./webgme-setup.json', 'utf8'));

const external = [
    'plugin/PluginBase',
    'plugin/PluginConfig',
    'text!./metadata.json',
    'fs',
    'path',
    'archiver',
    'webgme',
    'stams/gme-helpers',
    'stams/sm-langium',
    'stams/verification/expr-ast',
    'stams/verification/model-export',
    'stams/verification/constraints-export',
    'stams/verification/simulation-engine',
    'stams/verification/constraint-eval',
    'stams/verification/bounded-verifier',
    'stams/verification/settings',
    'stams/verification/verifier',
    'stams/verification/z3-runner',
    'stams/verification/smt-bmc',
    'stams/verification/smt-expr',
    'stams/verification/z3-verifier'
];

const pluginNames = Object.keys(webgmeSetup.components.plugins || {});

const commonBundles = [
    {
        input: 'src/common/sm-langium.ts',
        output: {
            file: 'build/stams/sm-langium.cjs',
            format: 'cjs',
            sourcemap: true,
            inlineDynamicImports: true
        },
        external: [],
        plugins: [
            resolve({
                preferBuiltins: true,
                exportConditions: ['node', 'import', 'default']
            }),
            commonjs(),
            json(),
            typescript({
                tsconfig: './tsconfig.json',
                compilerOptions: {
                    rootDir: '.',
                    outDir: 'build',
                    declaration: false,
                    declarationMap: false,
                    composite: false,
                    sourceMap: true
                }
            }),
            copy({
                targets: [
                    {
                        src: 'src/common/sm-langium.amd.js',
                        dest: 'build/stams',
                        rename: 'sm-langium.js'
                    }
                ]
            })
        ]
    }
];

export default [
    ...commonBundles,
    ...pluginNames.map((name) => {
    const tsEntry = path.join('src', 'plugins', name, `${name}.ts`);
    const jsEntry = path.join('src', 'plugins', name, `${name}.js`);

    let input = jsEntry;
    try {
        readFileSync(tsEntry);
        input = tsEntry;
    } catch {
        // use .js entry generated by webgme-cli
    }

    return {
        input,
        output: {
            file: path.join('build', 'plugins', name, `${name}.js`),
            format: 'amd',
            sourcemap: true
        },
        external,
        plugins: [
            json(),
            commonjs(),
            typescript({
                tsconfig: './tsconfig.json',
                compilerOptions: {
                    rootDir: '.',
                    outDir: 'build',
                    declaration: false,
                    declarationMap: false,
                    composite: false,
                    sourceMap: true
                }
            }),
            copy({
                targets: [
                    {
                        src: path.join('src', 'plugins', name, 'metadata.json'),
                        dest: path.join('build', 'plugins', name)
                    }
                ]
            })
        ]
    };
    })
];
