/*globals define*/
/*eslint-env node, browser*/

define([
    'plugin/PluginConfig',
    'text!./metadata.json',
    'plugin/PluginBase',
    'stams/gme-helpers'
], function (PluginConfig, pluginMetadata, PluginBase, GmeHelpers) {
    'use strict';

    pluginMetadata = JSON.parse(pluginMetadata);

    function ModelToText() {
        PluginBase.call(this);
        this.pluginMetadata = pluginMetadata;
    }

    ModelToText.metadata = pluginMetadata;
    ModelToText.prototype = Object.create(PluginBase.prototype);
    ModelToText.prototype.constructor = ModelToText;

    ModelToText.prototype.main = function (callback) {
        var self = this,
            core = self.core,
            config = self.getCurrentConfig(),
            filePath = config.fileNodePath,
            fileNode,
            machines,
            lines;

        function finish(err) {
            if (err) {
                callback(err, self.result);
                return;
            }
            self.result.setSuccess(true);
            callback(null, self.result);
        }

        self.result.setSuccess(false);

        if (!filePath) {
            core.setRegistry(self.rootNode, 'ModelToText_bootstrap', Date.now().toString());
            return self.save('bootstrap', finish);
        }

        fileNode = core.getNode(core.getRoot(self.rootNode), filePath);
        if (!fileNode || !GmeHelpers.isTypeOf(core, fileNode, GmeHelpers.META_TYPES.FILE)) {
            callback(new Error('fileNodePath must reference a File node'), self.result);
            return;
        }

        machines = GmeHelpers.getChildrenOfType(core, fileNode, GmeHelpers.META_TYPES.MACHINE);
        lines = ['// Generated by ModelToText (bootstrap)'];

        machines.forEach(function (machine) {
            lines.push('machine ' + core.getAttribute(machine, 'name') + ' {');
            lines.push('  // TODO(Phase 1): serialize states, events, transitions');
            lines.push('}');
        });

        core.setAttribute(fileNode, 'content', lines.join('\n'));
        self.logger.info('ModelToText bootstrap wrote ' + lines.length + ' lines to ' + filePath);
        self.save('model-to-text', finish);
    };

    ModelToText.configStructure = pluginMetadata.configStructure;
    return ModelToText;
});
